### ISSUE TITLE
TypeError when loading task json data

### ISSUE THREAD

**Issue by alanhamlett** [closeio/tasktiger#112]
```
Traceback (most recent call last):
  File "./test.py", line 4, in purge_tasktiger_error_queues
    count, tasks = Task.tasks_from_queue(tiger, queue, ERROR)
  File "./venv/lib/python3.5/site-packages/tasktiger/task.py", line 393, in tasks_from_queue
    data = json.loads(serialized_data)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
```

**Comment by thomasst** [comment]
What lead to this?
