### ISSUE TITLE
Pip install is missing /lua/execute_pipeline.lua

### ISSUE THREAD

**Issue by mxmzdlv** [closeio/tasktiger#60]
There seems to be a build issue with pip. Tasktiger installed through `pip install tasktiger` doesn't contain lua folder with execute_pipeline.lua:

```
Traceback (most recent call last):
  File "app.py", line 29, in <module>
    tiger = tasktiger.TaskTiger()
  File "/Users/maxim/code/gs-tracking/.env/lib/python3.6/site-packages/tasktiger/__init__.py", line 148, in __init__
    self.scripts = RedisScripts(self.connection)
  File "/Users/maxim/code/gs-tracking/.env/lib/python3.6/site-packages/tasktiger/redis_scripts.py", line 298, in __init__
    self._execute_pipeline = self.register_script_from_file('lua/execute_pipeline.lua')
  File "/Users/maxim/code/gs-tracking/.env/lib/python3.6/site-packages/tasktiger/redis_scripts.py", line 302, in register_script_from_file
    os.path.realpath(__file__)), filename)).read())
FileNotFoundError: [Errno 2] No such file or directory: '/Users/maxim/code/gs-tracking/.env/lib/python3.6/site-packages/tasktiger/lua/execute_pipeline.lua'
```
I checked the tar file on https://pypi.python.org/pypi/tasktiger/0.8.5 and lua folder is missing.

**Comment by thomasst** [comment]
Thanks! This was fixed in 0.9.1 with https://github.com/closeio/tasktiger/commit/f6f1cd80ebd316bb53188d8fe5db3ec79a044d48

Let me know if you still have any issues.
